name: Build and test application

on:
  # Triggers the workflow on push or pull request events on all branches except main
  push:
    branches-ignore:
      - main
  pull_request:
    branches-ignore:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Dummy Action
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: 'Hello World'
