name: Build and deploy application to Azure AKS Cluster
on:
  #push:
  #  branches: [ main ]
  #pull_request:
  #  branches: [ main ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
env:
  CONTAINER_REGISTRY: sgse2021containerregistry.azurecr.io
  CLUSTER_NAME: sgse2021AKSCluster
  RESOURCE_GROUP: sgse2021ResourceGroup
  MS_NAMESPACE: microservices
  IMAGE_NAME: test-app-front
  DOCKERFILE: ./Dockerfile
  MANIFESTFILE: ./manifests/test-app.yaml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
     
    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
    
    - name: Login to Azure Container Registry
      uses: Azure/docker-login@v1
      with:
        login-server: ${{ env.CONTAINER_REGISTRY }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
        
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
          context: ./
          file: ${{ env.DOCKERFILE }}
          push: true
          tags: "${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:latest"
          cache-from: type=gha,src=/tmp/.buildx-cache
          cache-to: type=gha,dest=/tmp/.buildx-cache-new
          
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
      
    # Temp fix
    # https://github.com/docker/build-push-action/issues/252
    # https://github.com/moby/buildkit/issues/1896
    - name: Move cache
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

#    - name: Azure authentication
#      uses: azure/login@v1
#      with:
#          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
#    - name: Login to Azure Container Registry
#      uses: Azure/docker-login@v1
#      with:
#        login-server: ${{ env.CONTAINER_REGISTRY }}
#        username: ${{ secrets.ACR_USERNAME }}
#        password: ${{ secrets.ACR_PASSWORD }}

#    - name: Set target AKS cluster
#      uses: Azure/aks-set-context@v1
#      with:
#        creds: ${{ secrets.AZURE_CREDENTIALS }}
#        cluster-name: ${{ env.CLUSTER_NAME }}
#        resource-group: ${{ env.RESOURCE_GROUP }}
        
    - id: file_changes
      uses: trilom/file-changes-action@v1.2.3
      with:
        output: ' '
    
    - name: print changed files
      run: |
        echo ${{ env.MANIFESTFILE }})
        
#    - if: contains(steps.file_changes.outputs.files, ${{ env.MANIFESTFILE }})
#      name: Deploy to k8s with manifest
#      uses: Azure/k8s-deploy@v1
#      with:
#        manifests: ${{ env.MANIFESTFILE }}
#        namespace: ${{ env.MS_NAMESPACE }}
        
#    - if: ! contains(steps.file_changes.outputs.files, ${{ env.MANIFESTFILE }})
#      name: Deploy to k8s
#      run: |
#        kubectl rollout restart deployment test-app-front
