name: Test action
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Print trigger
        run: |
          echo ${{ github.event }}
          echo ${{ github.event_name }}
      
      - id: file_changes
        uses: trilom/file-changes-action@v1.2.3
        with:
          output: ' '
          
      - if: contains(steps.file_changes.outputs.files, '.github/workflows/test.yml')
        name: File changed
        run: |
          echo "File changed"
